/** @type {import('tailwindcss').Config} */

module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],

  darkMode: ['class', '[data-theme]'],

  theme: {
    extend: {
      colors: {
        primary: {
          50: 'rgb(var(--primary-50-rgb) / <alpha-value>)',
          100: 'rgb(var(--primary-100-rgb) / <alpha-value>)',
          200: 'rgb(var(--primary-200-rgb) / <alpha-value>)',
          300: 'rgb(var(--primary-300-rgb) / <alpha-value>)',
          400: 'rgb(var(--primary-400-rgb) / <alpha-value>)',
          500: 'rgb(var(--primary-500-rgb) / <alpha-value>)',
          600: 'rgb(var(--primary-600-rgb) / <alpha-value>)',
          700: 'rgb(var(--primary-700-rgb) / <alpha-value>)',
          800: 'rgb(var(--primary-800-rgb) / <alpha-value>)',
          900: 'rgb(var(--primary-900-rgb) / <alpha-value>)',
          DEFAULT: 'rgb(var(--primary-rgb) / <alpha-value>)',
          foreground: 'rgb(var(--primary-foreground-rgb) / <alpha-value>)',
        },
        secondary: {
          50: 'rgb(var(--secondary-50-rgb) / <alpha-value>)',
          100: 'rgb(var(--secondary-100-rgb) / <alpha-value>)',
          200: 'rgb(var(--secondary-200-rgb) / <alpha-value>)',
          300: 'rgb(var(--secondary-300-rgb) / <alpha-value>)',
          400: 'rgb(var(--secondary-400-rgb) / <alpha-value>)',
          500: 'rgb(var(--secondary-500-rgb) / <alpha-value>)',
          600: 'rgb(var(--secondary-600-rgb) / <alpha-value>)',
          700: 'rgb(var(--secondary-700-rgb) / <alpha-value>)',
          800: 'rgb(var(--secondary-800-rgb) / <alpha-value>)',
          900: 'rgb(var(--secondary-900-rgb) / <alpha-value>)',
          DEFAULT: 'rgb(var(--secondary-rgb) / <alpha-value>)',
          foreground: 'rgb(var(--secondary-foreground-rgb) / <alpha-value>)',
        },
        success: {
          50: 'rgb(var(--success-50-rgb) / <alpha-value>)',
          100: 'rgb(var(--success-100-rgb) / <alpha-value>)',
          200: 'rgb(var(--success-200-rgb) / <alpha-value>)',
          300: 'rgb(var(--success-300-rgb) / <alpha-value>)',
          400: 'rgb(var(--success-400-rgb) / <alpha-value>)',
          500: 'rgb(var(--success-500-rgb) / <alpha-value>)',
          600: 'rgb(var(--success-600-rgb) / <alpha-value>)',
          700: 'rgb(var(--success-700-rgb) / <alpha-value>)',
          800: 'rgb(var(--success-800-rgb) / <alpha-value>)',
          900: 'rgb(var(--success-900-rgb) / <alpha-value>)',
          DEFAULT: 'rgb(var(--success-rgb) / <alpha-value>)',
          foreground: 'rgb(var(--success-foreground-rgb) / <alpha-value>)',
        },
        warning: {
          50: 'rgb(var(--warning-50-rgb) / <alpha-value>)',
          100: 'rgb(var(--warning-100-rgb) / <alpha-value>)',
          200: 'rgb(var(--warning-200-rgb) / <alpha-value>)',
          300: 'rgb(var(--warning-300-rgb) / <alpha-value>)',
          400: 'rgb(var(--warning-400-rgb) / <alpha-value>)',
          500: 'rgb(var(--warning-500-rgb) / <alpha-value>)',
          600: 'rgb(var(--warning-600-rgb) / <alpha-value>)',
          700: 'rgb(var(--warning-700-rgb) / <alpha-value>)',
          800: 'rgb(var(--warning-800-rgb) / <alpha-value>)',
          900: 'rgb(var(--warning-900-rgb) / <alpha-value>)',
          DEFAULT: 'rgb(var(--warning-rgb) / <alpha-value>)',
          foreground: 'rgb(var(--warning-foreground-rgb) / <alpha-value>)',
        },
        danger: {
          50: 'rgb(var(--danger-50-rgb) / <alpha-value>)',
          100: 'rgb(var(--danger-100-rgb) / <alpha-value>)',
          200: 'rgb(var(--danger-200-rgb) / <alpha-value>)',
          300: 'rgb(var(--danger-300-rgb) / <alpha-value>)',
          400: 'rgb(var(--danger-400-rgb) / <alpha-value>)',
          500: 'rgb(var(--danger-500-rgb) / <alpha-value>)',
          600: 'rgb(var(--danger-600-rgb) / <alpha-value>)',
          700: 'rgb(var(--danger-700-rgb) / <alpha-value>)',
          800: 'rgb(var(--danger-800-rgb) / <alpha-value>)',
          900: 'rgb(var(--danger-900-rgb) / <alpha-value>)',
          DEFAULT: 'rgb(var(--danger-rgb) / <alpha-value>)',
          foreground: 'rgb(var(--danger-foreground-rgb) / <alpha-value>)',
        },
        peak: {
          50: 'rgb(var(--peak-50-rgb) / <alpha-value>)',
          100: 'rgb(var(--peak-100-rgb) / <alpha-value>)',
          200: 'rgb(var(--peak-200-rgb) / <alpha-value>)',
          300: 'rgb(var(--peak-300-rgb) / <alpha-value>)',
          400: 'rgb(var(--peak-400-rgb) / <alpha-value>)',
          500: 'rgb(var(--peak-500-rgb) / <alpha-value>)',
          600: 'rgb(var(--peak-600-rgb) / <alpha-value>)',
          700: 'rgb(var(--peak-700-rgb) / <alpha-value>)',
          800: 'rgb(var(--peak-800-rgb) / <alpha-value>)',
          900: 'rgb(var(--peak-900-rgb) / <alpha-value>)',
          DEFAULT: 'rgb(var(--peak-rgb) / <alpha-value>)',
          foreground: 'rgb(var(--peak-foreground-rgb) / <alpha-value>)',
        },
        recovery: {
          50: 'rgb(var(--recovery-50-rgb) / <alpha-value>)',
          100: 'rgb(var(--recovery-100-rgb) / <alpha-value>)',
          200: 'rgb(var(--recovery-200-rgb) / <alpha-value>)',
          300: 'rgb(var(--recovery-300-rgb) / <alpha-value>)',
          400: 'rgb(var(--recovery-400-rgb) / <alpha-value>)',
          500: 'rgb(var(--recovery-500-rgb) / <alpha-value>)',
          600: 'rgb(var(--recovery-600-rgb) / <alpha-value>)',
          700: 'rgb(var(--recovery-700-rgb) / <alpha-value>)',
          800: 'rgb(var(--recovery-800-rgb) / <alpha-value>)',
          900: 'rgb(var(--recovery-900-rgb) / <alpha-value>)',
          DEFAULT: 'rgb(var(--recovery-rgb) / <alpha-value>)',
          foreground: 'rgb(var(--recovery-foreground-rgb) / <alpha-value>)',
        },

        neutral: {
          50: 'rgb(var(--neutral-50-rgb) / <alpha-value>)',
          100: 'rgb(var(--neutral-100-rgb) / <alpha-value>)',
          200: 'rgb(var(--neutral-200-rgb) / <alpha-value>)',
          300: 'rgb(var(--neutral-300-rgb) / <alpha-value>)',
          400: 'rgb(var(--neutral-400-rgb) / <alpha-value>)',
          500: 'rgb(var(--neutral-500-rgb) / <alpha-value>)',
          600: 'rgb(var(--neutral-600-rgb) / <alpha-value>)',
          700: 'rgb(var(--neutral-700-rgb) / <alpha-value>)',
          800: 'rgb(var(--neutral-800-rgb) / <alpha-value>)',
          900: 'rgb(var(--neutral-900-rgb) / <alpha-value>)',
        },

        surface: 'rgb(var(--surface-rgb) / <alpha-value>)',
        background: 'rgb(var(--bg-rgb) / <alpha-value>)',
        foreground: 'rgb(var(--foreground-rgb) / <alpha-value>)',
        muted: 'rgb(var(--muted-rgb) / <alpha-value>)',
        border: 'rgb(var(--border-rgb) / <alpha-value>)',

        activity: {
          run: 'var(--activity-run)',
          ride: 'var(--activity-ride)',
          swim: 'var(--activity-swim)',
          hike: 'var(--activity-hike)',
          walk: 'var(--activity-walk)',
          ski: 'var(--activity-ski)',
          trail: 'var(--activity-trail)',
          rowing: 'var(--activity-rowing)',
          other: 'var(--activity-other)',
        },
        'hr-zone': {
          1: 'var(--hr-zone-1)',
          2: 'var(--hr-zone-2)',
          3: 'var(--hr-zone-3)',
          4: 'var(--hr-zone-4)',
          5: 'var(--hr-zone-5)',
        },
        'power-zone': {
          1: 'var(--power-zone-1)',
          2: 'var(--power-zone-2)',
          3: 'var(--power-zone-3)',
          4: 'var(--power-zone-4)',
          5: 'var(--power-zone-5)',
          6: 'var(--power-zone-6)',
          7: 'var(--power-zone-7)',
        },
        form: {
          peak: 'var(--form-peak)',
          fresh: 'var(--form-fresh)',
          normal: 'var(--form-normal)',
          fatigued: 'var(--form-fatigued)',
          overtrained: 'var(--form-overtrained)',
        },
      },

      zIndex: {
        base: '0', raised: '10', content: '20', fixed: '20',
        sticky: '30', dropdown: '40', 'modal-backdrop': '45',
        modal: '50', drawer: '50', toast: '60', tooltip: '70', max: '9999',
      },

      spacing: {
        '0': '0px', '1': '4px', '2': '8px', '3': '12px', '4': '16px',
        '5': '20px', '6': '24px', '7': '28px', '8': '32px', '9': '36px',
        '10': '40px', '11': '44px', '12': '48px', '14': '56px', '16': '64px',
        '20': '80px', '24': '96px', '28': '112px', '32': '128px', '36': '144px',
        '40': '160px', '44': '176px', '48': '192px', '52': '208px', '56': '224px', '64': '256px',
      },

      borderRadius: {
        none: '0px', sm: '6px', md: '8px', lg: '12px', xl: '16px',
        '2xl': '24px', '3xl': '32px', full: '9999px',
        button: 'var(--radius-button)',
        card: 'var(--radius-card)',
        input: 'var(--radius-input)',
        badge: 'var(--radius-badge)',
      },

      fontFamily: {
        sans: ['var(--font-sans)'],
        display: ['var(--font-display)'],
        mono: ['var(--font-mono)'],
        body: ['var(--font-sans)'],
      },

      fontSize: {
        xs: '12px', sm: '14px', md: '16px', lg: '18px', xl: '20px',
        '2xl': '24px', '3xl': '30px', '4xl': '36px', '5xl': '48px',
        '6xl': '60px', '7xl': '72px', '8xl': '96px',
        hero: '72px', 'hero-mobile': '40px',
        data: '24px', 'data-sm': '20px',
        stat: '28px', 'stat-sm': '20px', 'stat-label': '14px',
      },

      lineHeight: {
        xs: '16px', sm: '20px', md: '24px', lg: '28px', xl: '32px', '2xl': '36px',
        hero: '80px', 'hero-mobile': '48px', data: '32px', 'data-sm': '28px',
      },

      boxShadow: {
        xs: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        sm: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
        md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        card: 'var(--shadow-card)',
        'card-hover': 'var(--shadow-card-hover)',
        elevated: 'var(--shadow-elevated)',
        'button-primary': 'var(--shadow-button-primary)',
        'button-primary-hover': 'var(--shadow-button-primary-hover)',
        'inner-sm': 'inset 0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        'inner-md': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.05)',
      },

      opacity: {
        disabled: 'var(--opacity-disabled)',
        muted: 'var(--opacity-muted)',
        subtle: 'var(--opacity-subtle)',
        light: 'var(--opacity-light)',
        medium: 'var(--opacity-medium)',
        strong: 'var(--opacity-strong)',
        hover: 'var(--opacity-hover)',
        active: 'var(--opacity-active)',
      },

      transitionDuration: {
        instant: '0ms', fast: '150ms', normal: '200ms',
        slow: '300ms', slower: '400ms', slowest: '500ms',
      },

      transitionTimingFunction: {
        linear: 'linear', ease: 'ease', 'ease-in': 'ease-in',
        'ease-out': 'ease-out', 'ease-in-out': 'ease-in-out',
        spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        smooth: 'cubic-bezier(0.4, 0, 0.2, 1)',
        bounce: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
      },

      transitionProperty: {
        'transform-opacity': 'transform, opacity',
        'all': 'all',
      },

      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.2s ease-out',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'float': 'float 3s ease-in-out infinite',
        'gradient-shift': 'gradientShift 8s ease infinite',
        'count-up': 'countUp 0.5s ease-out',
        'spin': 'spin 1s linear infinite',
        'ping': 'ping 1s ease-out infinite',
        'bounce': 'bounce 1s ease-in-out infinite',
      },

      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { opacity: '0', transform: 'translateY(10px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideDown: { '0%': { opacity: '0', transform: 'translateY(-10px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        pulseSoft: { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.7' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        float: { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
        gradientShift: { '0%, 100%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' } },
        countUp: { '0%': { opacity: '0', transform: 'translateY(10px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        spin: { '0%': { transform: 'rotate(0deg)' }, '100%': { transform: 'rotate(360deg)' } },
        ping: { '75%, 100%': { transform: 'scale(2)', opacity: '0' } },
        bounce: { '0%, 100%': { transform: 'translateY(-25%)', animationTimingFunction: 'cubic-bezier(0.8,0,1,1)' }, '50%': { transform: 'none', animationTimingFunction: 'cubic-bezier(0,0,0.2,1)' } },
      },

      screens: {
        xs: '480px', sm: '640px', md: '768px', lg: '1024px',
        xl: '1280px', '2xl': '1536px', '3xl': '1920px',
      },
    },
  },

  plugins: [
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms'),
    require('tailwindcss-animate'),
  ],
};
